---
- name: Create the automation gateway proxy container
  containers.podman.podman_container:
    name: automation-gateway-proxy
    image: '{{ _gateway_proxy_image }}'
    generate_systemd:
      container_prefix: ''
      path: '{{ ansible_user_dir }}/.config/systemd/user'
      separator: ''
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    command: '/usr/bin/envoy --config-path /etc/envoy/envoy.yaml'
    volume: '{{ _envoy_volumes }}'
    label: '{{ _autoupdate_label }}'
    state: created
    recreate: '{{ __containers_recreate | default(false) }}'
  notify: Restart automation gateway proxy

- name: Create the automation gateway container
  containers.podman.podman_container:
    name: automation-gateway
    image: '{{ _gateway_image }}'
    command: '/usr/bin/supervisord --configuration /etc/supervisord.conf'
    generate_systemd:
      container_prefix: ''
      path: '{{ ansible_user_dir }}/.config/systemd/user'
      separator: ''
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    mount:
      - 'type=tmpfs,destination=/run/nginx,U=true'
      - 'type=tmpfs,destination=/var/cache/ansible-automation-platform/gateway,U=true'
    secrets: '{{ _django_secrets }}'
    volume: '{{ _web_volumes }}'
    env: '{{ _common_env }}'
    label: '{{ _autoupdate_label }}'
    state: created
    recreate: '{{ __containers_recreate | default(false) }}'
  notify: Restart automation gateway
...
