---
- name: Set gateway hostname, port(s) and protocol
  ansible.builtin.set_fact:
    _gateway_hostname: '{{ routable_hostname | default(ansible_host) }}'
    _gateway_port: '{{ (gateway_nginx_disable_https | bool) | ternary(gateway_nginx_http_port, gateway_nginx_https_port) }}'
    _gateway_ports: ['{{ gateway_nginx_http_port }}']
    _gateway_protocol: '{{ (gateway_nginx_disable_https | bool) | ternary("http", "https") }}'
    _gateway_proxy_port: '{{ (envoy_disable_https | bool) | ternary(envoy_http_port, envoy_https_port) }}'
    _gateway_proxy_ports: ['{{ envoy_http_port }}']
    _gateway_proxy_protocol: '{{ (envoy_disable_https | bool) | ternary("http", "https") }}'

- name: Add https port to gateway port list
  ansible.builtin.set_fact:
    _gateway_ports: '{{ _gateway_ports | union([gateway_nginx_https_port]) }}'
  when: not gateway_nginx_disable_https | bool

- name: Add https port to gateway proxy port list
  ansible.builtin.set_fact:
    _gateway_proxy_ports: '{{ _gateway_proxy_ports | union([envoy_https_port]) }}'
  when: not envoy_disable_https | bool

- name: Combine gateway ports
  ansible.builtin.set_fact:
    _gateway_ports: '{{ _gateway_ports | union(_gateway_proxy_ports) }}'

- name: Set gateway URL
  ansible.builtin.set_fact:
    _gateway_proxy_url: '{{ gateway_main_url | default(_gateway_proxy_protocol + "://" + _gateway_hostname + ":" + _gateway_proxy_port) }}'

- name: Set gateway IPs
  ansible.builtin.set_fact:
    _gateway_ips: '{{ _gateway_ips | default([]) | union(["IP:" + item]) }}'
  loop: '{{ ansible_all_ipv4_addresses + ansible_all_ipv6_addresses }}'

- name: Add postgresql container to requires when on the same node
  ansible.builtin.set_fact:
    gateway_container_requires: '{{ gateway_container_requires | union(["postgresql"]) }}'
  when: inventory_hostname in groups.get('database', [])

- name: Set gateway redis hostname
  ansible.builtin.set_fact:
    _gateway_redis_hostname: '{{ gateway_redis_host | default(_gateway_hostname) }}'

- name: Set gateway redis proto/host facts
  ansible.builtin.set_fact:
    _gateway_redis_proto: '{{ (gateway_redis_disable_tls | bool) | ternary("redis", "rediss") }}'
    _gateway_redis_host: '{{ hostvars[groups["automationgateway"][0]]["_gateway_redis_hostname"] }}'

- name: Set gateway redis url facts
  ansible.builtin.set_fact:
    _gateway_redis_url: '{{ _gateway_redis_proto }}://{{ _gateway_redis_creds }}@{{ _gateway_redis_host }}:{{ gateway_redis_port }}'
  vars:
    _gateway_redis_creds: '{{ gateway_redis_username }}:{{ hostvars["localhost"]["_gateway_redis_password"] }}'
  no_log: true

- name: Append redis database when standalone
  ansible.builtin.set_fact:
    _gateway_redis_url: '{{ _gateway_redis_url }}/{{ gateway_redis_cache_db }}'
  no_log: true
  when: redis_mode | default('cluster') == 'standalone'

- name: Set redis cluster hostnames
  ansible.builtin.set_fact:
    _redis_cluster_hostnames: '{{ _redis_hostnames | product([gateway_redis_port | string]) | map("join", ":") | join(",") }}'
  vars:
    _redis_hostnames: '{{ groups["redis"] | map("extract", hostvars) | map(attribute="_redis_hostname") }}'
  run_once: true
  when: redis_mode | default('cluster') == 'cluster'

- name: Set automation gateway volumes
  ansible.builtin.set_fact:
    _common_env:
      DJANGO_SETTINGS_MODULE: 'aap_gateway_api.settings'
    _django_secrets:
      - 'gateway_secret_key,type=mount,target=/etc/ansible-automation-platform/gateway/SECRET_KEY'
      - 'gateway_admin_password,type=env,target=DJANGO_SUPERUSER_PASSWORD'
      - 'gateway_redis_url,type=env,target=REDIS_URL'
    _common_volumes:
      - '{{ _ca_tls_dir }}/extracted:/etc/pki/ca-trust/extracted:z'
    _envoy_volumes:
      - '{{ envoy_conf_dir }}/envoy.yaml:/etc/envoy/envoy.yaml:ro,z'
    _service_volumes:
      - '{{ supervisor_run_dir }}:/run/supervisor:z'
      - '{{ gateway_conf_dir }}/settings.py:/etc/ansible-automation-platform/gateway/settings.py:ro,z'
      - '{{ gateway_conf_dir }}/supervisord.conf:/etc/supervisord.conf:ro,z'
    _nginx_volumes:
      - '{{ gateway_nginx_conf_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro,z'
      - '{{ gateway_conf_dir }}/uwsgi.ini:/etc/ansible-automation-platform/gateway/uwsgi.ini:ro,z'
      - 'gateway_nginx:/var/lib/nginx:U'

- name: Add postgresql password secret to secrets
  ansible.builtin.set_fact:
    _django_secrets: '{{ _django_secrets + _postgresql_db_secret }}'
  vars:
    _postgresql_db_secret:
      - 'gateway_db_password,type=env,target=DATABASE_PASSWORD'
  when: not gateway_pg_cert_auth | bool

- name: Add postgresql socket directory to common automation gateway volumes
  ansible.builtin.set_fact:
    _common_volumes: '{{ _common_volumes + _postgresql_volumes }}'
  vars:
    _postgresql_volumes:
      - '{{ gateway_pg_socket }}:{{ gateway_pg_socket }}:z'
  when: gateway_pg_socket is defined

- name: Set web automation gateway and proxy volumes
  ansible.builtin.set_fact:
    _envoy_volumes: '{{ _common_volumes + _envoy_volumes }}'
    _web_volumes: '{{ _common_volumes + _service_volumes + _nginx_volumes }}'

- name: Add postgresql tls to automation gateway volumes
  ansible.builtin.set_fact:
    _web_volumes: '{{ _web_volumes + _postgresql_tls_volumes }}'
  vars:
    _postgresql_tls_volumes:
      - '{{ gateway_conf_dir }}/postgresql.cert:/etc/ansible-automation-platform/gateway/postgresql.cert:ro,z'
      - '{{ gateway_conf_dir }}/postgresql.key:/etc/ansible-automation-platform/gateway/postgresql.key:ro,z'
  when: gateway_pg_cert_auth | bool

- name: Add tls to automation gateway volumes
  ansible.builtin.set_fact:
    _web_volumes: '{{ _web_volumes + _tls_volumes }}'
  vars:
    _tls_volumes:
      - '{{ gateway_conf_dir }}/gateway.cert:/etc/ansible-automation-platform/gateway/gateway.crt:ro,z'
      - '{{ gateway_conf_dir }}/gateway.key:/etc/ansible-automation-platform/gateway/gateway.key:ro,z'
  when: not gateway_nginx_disable_https | bool

- name: Add tls to automation gateway proxy volumes
  ansible.builtin.set_fact:
    _envoy_volumes: '{{ _envoy_volumes + _tls_volumes }}'
  vars:
    _tls_volumes:
      - '{{ gateway_conf_dir }}/gateway.cert:/etc/ansible-automation-platform/gateway/gateway.crt:ro,z'
      - '{{ gateway_conf_dir }}/gateway.key:/etc/ansible-automation-platform/gateway/gateway.key:ro,z'
  when: not envoy_disable_https | bool

- name: Add redis tls to automation gateway volumes
  ansible.builtin.set_fact:
    _web_volumes: '{{ _web_volumes + _redis_tls_volumes }}'
  vars:
    _redis_tls_volumes:
      - '{{ gateway_conf_dir }}/redis.cert:/etc/ansible-automation-platform/gateway/redis.cert:ro,z'
      - '{{ gateway_conf_dir }}/redis.key:/etc/ansible-automation-platform/gateway/redis.key:ro,z'
  when: not gateway_redis_disable_tls | bool

- name: Render proxy variables
  ansible.builtin.set_fact:
    gateway_proxy_vars: '{{ lookup("template", "proxy.yml.j2") | from_yaml }}'

- name: Set systemd requires
  ansible.builtin.set_fact:
    __systemd_requires: '{{ gateway_container_requires | sort | product([".service"]) | map("join") | list }}'
...
