---
- name: Manage automation gateway firewalld ports
  ansible.posix.firewalld:
    port: '{{ item }}/tcp'
    permanent: true
    state: '{{ __firewalld_state }}'
    immediate: true
    zone: '{{ gateway_firewall_zone }}'
  become: true
  loop: '{{ _gateway_ports }}'
  when:
    - ansible_facts.services.get('firewalld.service', {}) | length
    - ansible_facts.services['firewalld.service']['status'] == 'enabled'
...
