---
- name: Set automation gateway facts
  ansible.builtin.include_tasks: facts.yml

- name: Create podman volumes
  ansible.builtin.include_tasks: volumes.yml
  vars:
    __volume_state: present

- name: Configure postgresql
  ansible.builtin.include_tasks: postgresql.yml
  args:
    apply:
      run_once: true
  when: groups.get('database', []) | length == 1 or postgresql_admin_password is defined

- name: Configure automation gateway
  ansible.builtin.include_tasks: config.yml

- name: Configure TLS or nginx
  ansible.builtin.include_tasks: tls.yml
  when: not envoy_disable_https | bool or not gateway_nginx_disable_https | bool

- name: Configure TLS for redis
  ansible.builtin.include_tasks: tls_redis.yml
  when: not gateway_redis_disable_tls | bool

- name: Configure TLS for postgresql
  ansible.builtin.include_tasks: tls_postgresql.yml
  when: gateway_pg_cert_auth | bool

- name: Configure nginx
  ansible.builtin.include_tasks: nginx.yml

- name: Configure supervisor
  ansible.builtin.include_tasks: supervisor.yml

- name: Configure podman secrets
  ansible.builtin.include_tasks: secrets.yml

- name: Handle container image update
  ansible.builtin.include_tasks: update.yml

- name: Configure containers
  ansible.builtin.include_tasks: containers.yml
  vars:
    __containers_recreate: '{{ __gateway_recreate }}'

- name: Initialize data
  ansible.builtin.include_tasks: init.yml

- name: Ensure automation gateway containers are enabled and started
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_enabled: true
    __systemd_state: started

- name: Add firewalld rules
  ansible.builtin.include_tasks: firewalld.yml
  vars:
    __firewalld_state: enabled
...
