---
- name: Get sysctl net.ipv4.ip_unprivileged_port_start setting
  ansible.builtin.slurp:
    src: /proc/sys/net/ipv4/ip_unprivileged_port_start
  register: _sysctl_cmd

- name: Allow rootless automation gateway containers to bind from port 80 onwards
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '{{ _gateway_ports | union(_sysctl_unprivileged_port_start) | min }}'
    sysctl_set: true
    state: present
    reload: true
  become: true
  vars:
    _sysctl_unprivileged_port_start: "[{{ _sysctl_cmd['content'] | b64decode }}]"
  when: (_gateway_ports | min) < 1024

- name: Create the nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: '{{ gateway_nginx_conf_dir }}/nginx.conf'
    mode: '0640'
  notify: Restart automation gateway
...
