---
- name: Get all podman secrets
  containers.podman.podman_secret_info:
  register: _secrets

- name: Create the gateway admin password secret
  containers.podman.podman_secret:
    name: gateway_admin_password
    data: '{{ gateway_admin_password }}'
    skip_existing: '{{ _podman_idempotence | ternary(omit, true) }}'
    force: '{{ _podman_idempotence | ternary(omit, true) }}'

- name: Create the gateway db_password secret
  containers.podman.podman_secret:
    name: gateway_db_password
    data: '{{ gateway_pg_password }}'
    skip_existing: '{{ _podman_idempotence | ternary(omit, true) }}'
    force: '{{ _podman_idempotence | ternary(omit, true) }}'
  notify: Restart automation gateway
  when: not gateway_pg_cert_auth | bool

- name: Create the gateway redis url secret
  containers.podman.podman_secret:
    name: gateway_redis_url
    data: '{{ _gateway_redis_url }}'
    skip_existing: '{{ _podman_idempotence | ternary(omit, true) }}'
    force: '{{ _podman_idempotence | ternary(omit, true) }}'
  notify: Restart automation gateway

- name: Get the existing gateway secret key secret
  containers.podman.podman_container:
    name: gateway-secret-key-secret
    image: '{{ _gateway_image }}'
    command: cat /run/secrets/gateway_secret_key
    detach: false
    rm: true
    secrets: ['gateway_secret_key']
  register: _gateway_secret_key
  no_log: true
  run_once: true
  changed_when: false
  when: _secrets.secrets | map(attribute='Spec') | selectattr('Name', 'equalto', 'gateway_secret_key') | length > 0

- name: Set the gateway secret key secret fact
  ansible.builtin.set_fact:
    __gateway_secret_key: '{{ _gateway_secret_key.stdout | default(gateway_secret_key) | default(_key_generated) }}'
  vars:
    _key_generated: '{{ lookup("ansible.builtin.password", "/dev/null chars=ascii_letters,digits length=128") }}'
  no_log: true
  run_once: true

- name: Create the gateway secret_key secret
  containers.podman.podman_secret:
    name: gateway_secret_key
    data: '{{ __gateway_secret_key }}'
    skip_existing: true
  notify: Restart automation gateway

- name: Get all podman secrets after update
  containers.podman.podman_secret_info:
  register: _secrets_update

- name: Set gateway recreate container fact
  ansible.builtin.set_fact:
    __gateway_recreate: '{{ _gateway_before | difference(_gateway_after) | length > 0 }}'
  vars:
    _gateway_before: '{{ _secrets.secrets | map(attribute="ID") }}'
    _gateway_after: '{{ _secrets_update.secrets | map(attribute="ID") }}'
...
