---
- name: Create the supervisor directory
  ansible.builtin.file:
    path: '{{ supervisor_run_dir }}'
    mode: '0770'
    state: directory

- name: Create the supervisor configuration
  ansible.builtin.template:
    src: supervisord.conf.j2
    dest: '{{ gateway_conf_dir }}/supervisord.conf'
    mode: '0640'
  notify: Restart automation gateway
