---
- name: Set facts for systemd services
  ansible.builtin.set_fact:
    __services:
      - automation-gateway.service
      - automation-gateway-proxy.service

- name: Manage automation gateway containers via systemd
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: '{{ __systemd_state | default("started") }}'
    enabled: '{{ __systemd_enabled | default(true) }}'
    scope: user
    daemon_reload: true
  loop: '{{ __services }}'
...
