---
- name: Generate redis TLS certificate and key
  when:
    - gateway_redis_tls_cert is not defined
    - gateway_redis_tls_key is not defined
  block:
    - name: Install python-cryptography
      ansible.builtin.package:
        name: python3-cryptography
      become: true
      when: not ostree | bool

    - name: Check the current gateway redis private key
      ansible.builtin.stat:
        path: '{{ gateway_conf_dir }}/redis.key'
      register: _gateway_redis_tls_key

    - name: Generate a private key for redis
      community.crypto.openssl_privatekey:
        path: '{{ gateway_conf_dir }}/redis.key'
        mode: '0400'
      when: not _gateway_redis_tls_key.stat.exists | bool

    - name: Check the current gateway redis certificate
      ansible.builtin.stat:
        path: '{{ gateway_conf_dir }}/redis.cert'
      register: _gateway_redis_tls_cert

    - name: Create the gateway redis TLS certificate
      when: not _gateway_redis_tls_cert.stat.exists | bool
      block:
        - name: Generate a certificate signing request for redis
          community.crypto.openssl_csr_pipe:
            common_name: '{{ _gateway_redis_hostname }}'
            country_name: 'US'
            locality_name: 'Raleigh'
            organization_name: 'Red Hat'
            organizational_unit_name: 'Ansible'
            state_or_province_name: 'North Carolina'
            subject_alt_name: '{{ [_gateway_redis_hostname | ansible.containerized_installer.subject_alt_name] | union(_gateway_ips) }}'
            privatekey_path: '{{ gateway_conf_dir }}/redis.key'
          register: _gateway_redis_csr

        - name: Generate a self signed x509 certificate for redis
          community.crypto.x509_certificate:
            path: '{{ gateway_conf_dir }}/redis.cert'
            csr_content: '{{ _gateway_redis_csr.csr }}'
            privatekey_path: '{{ gateway_conf_dir }}/redis.key'
            provider: ownca
            ownca_path: '{{ _ca_tls_dir }}/ca.cert'
            ownca_privatekey_path: '{{ _ca_tls_dir }}/ca.key'
            ownca_privatekey_passphrase: '{{ ca_tls_key_passphrase | default(omit) }}'
            mode: '0640'

- name: Import redis TLS certificate and key
  when:
    - gateway_redis_tls_cert is defined
    - gateway_redis_tls_key is defined
  block:
    - name: Copy redis TLS certificate
      ansible.builtin.copy:
        src: '{{ gateway_redis_tls_cert }}'
        dest: '{{ gateway_conf_dir }}/redis.cert'
        mode: '0640'
        remote_src: '{{ gateway_tls_remote | default(false) }}'
      notify: Restart automation gateway

    - name: Copy redis TLS key
      ansible.builtin.copy:
        src: '{{ gateway_redis_tls_key }}'
        dest: '{{ gateway_conf_dir }}/redis.key'
        mode: '0400'
        remote_src: '{{ gateway_tls_remote | default(false) }}'
      notify: Restart automation gateway
...
