collections:
- name: cloud-aws_ops-3.0.0.tar.gz
  version: 3.0.0
- name: cloud-aws_troubleshooting-3.0.0.tar.gz
  version: 3.0.0
- name: cloud-azure_ops-4.0.1.tar.gz
  version: 4.0.1
- name: cloud-gcp_ops-2.0.0.tar.gz
  version: 2.0.0
- name: cloud-terraform_ops-1.0.0.tar.gz
  version: 1.0.0
- name: cloud-vmware_ops-1.5.1.tar.gz
  version: 1.5.1
- name: edge-microshift-1.0.3.tar.gz
  version: 1.0.3
- name: infra-aap_utilities-2.5.1.tar.gz
  version: 2.5.1
- name: infra-ah_configuration-2.0.6.tar.gz
  version: 2.0.6
- name: infra-ansible_rekey_variables-1.1.4.tar.gz
  version: 1.1.4
- name: infra-controller_configuration-2.9.0.tar.gz
  version: 2.9.0
- name: infra-convert2rhel-1.2.1.tar.gz
  version: 1.2.1
- name: infra-eda_configuration-1.1.0.tar.gz
  version: 1.1.0
- name: infra-ee_utilities-3.2.0.tar.gz
  version: 3.2.0
- name: infra-leapp-1.4.0.tar.gz
  version: 1.4.0
- name: infra-lvm_snapshots-2.1.0.tar.gz
  version: 2.1.0
- name: infra-middleware_ocpv-1.0.0.tar.gz
  version: 1.0.0
- name: infra-osbuild-2.3.0.tar.gz
  version: 2.3.0
- name: network-acls-3.0.0.tar.gz
  version: 3.0.0
- name: network-backup-3.0.0.tar.gz
  version: 3.0.0
- name: network-base-6.0.0.tar.gz
  version: 6.0.0
- name: network-bgp-6.0.1.tar.gz
  version: 6.0.1
- name: network-interfaces-5.0.0.tar.gz
  version: 5.0.0
- name: network-ospf-5.0.0.tar.gz
  version: 5.0.0
- name: network-telemetry-3.0.0.tar.gz
  version: 3.0.0
- name: network-vpn-4.0.0.tar.gz
  version: 4.0.0
