---
- name: Ensure registry username and password are provided
  ansible.builtin.assert:
    that:
      - registry_username is defined
      - registry_username | length
      - registry_password is defined
      - registry_password | length
    fail_msg: 'registry_username and registry_password must be set when registry_auth=true'
  when:
    - not bundle_install | default(false) | bool
    - registry_auth | default(true) | bool

- name: Include database checks
  ansible.builtin.include_tasks: database.yml

- name: Include redis checks
  ansible.builtin.include_tasks: redis.yml

- name: Include controller checks
  ansible.builtin.include_tasks: automationcontroller.yml
  when: groups.get('automationcontroller', []) | length > 0

- name: Include hub checks
  ansible.builtin.include_tasks: automationhub.yml
  when: groups.get('automationhub', []) | length > 0

- name: Include eda checks
  ansible.builtin.include_tasks: automationeda.yml
  when: groups.get('automationeda', []) | length > 0

- name: Include receptor checks
  ansible.builtin.include_tasks: receptor.yml
  when: groups.get('execution_nodes', []) | length > 0

- name: Include gateway checks
  ansible.builtin.include_tasks: automationgateway.yml

- name: Include bundle checks
  when: bundle_install | default(false) | bool
  block:
    - name: Ensure bundle_dir is provided
      ansible.builtin.assert:
        that:
          - bundle_dir is defined
          - bundle_dir | length
        fail_msg: 'bundle_dir must be set when bundle_install=true'

    - name: Check the images directory
      ansible.builtin.stat:
        path: '{{ bundle_dir }}/images'
      register: _bundle_images

    - name: Ensure the images directory exists
      ansible.builtin.assert:
        that:
          - _bundle_images.stat.exists | bool
          - _bundle_images.stat.isdir | bool
        fail_msg: 'The bundle directory must contain an images directory'

    - name: Check the collections directory
      ansible.builtin.stat:
        path: '{{ bundle_dir }}/collections'
      register: _bundle_collections

    - name: Ensure the collections directory exists
      ansible.builtin.assert:
        that:
          - _bundle_collections.stat.exists | bool
          - _bundle_collections.stat.isdir | bool
        fail_msg: 'The bundle directory must contain a collections directory'
      when: hub_seed_collections | default(true) | bool

- name: Validate feature flags
  when: feature_flags is defined
  block:
    - name: Ensure feature_flags is a dictonary
      ansible.builtin.assert:
        that:
          - feature_flags is not string
          - feature_flags is iterable
          - feature_flags is mapping
        fail_msg: 'feature_flags variable must be a dictionary'

    - name: Ensure feature_flags keys/values are valid
      ansible.builtin.assert:
        that:
          - item.key | upper is match('^FEATURE_')
          - item.value is boolean
        fail_msg: 'keys must be prefixed with feature_ and values must be boolean'
      loop: '{{ feature_flags | dict2items }}'
...
