---
- name: Ensure redis mode is a valid choice
  ansible.builtin.assert:
    that:
      - redis_mode in ['cluster', 'standalone']
    fail_msg: 'Invalid redis mode value.'
  when: redis_mode is defined

- name: Ensure redis cluster is correctly configured
  ansible.builtin.assert:
    that:
      - groups.get('redis', []) | length >= 6
    fail_msg: 'A [redis] group with at least 6 nodes if required for redis cluster mode'
  when: redis_mode | default('cluster') == 'cluster'
...
