---
### container
container_log_driver: journald

### common
aap_volumes_dir: '{{ ansible_user_dir }}/aap'

### eda
eda_admin_user: admin
eda_admin_email: admin@example.com
eda_firewall_zone: public
eda_conf_dir: '{{ aap_volumes_dir }}/eda/etc'
eda_container_requires:
  - redis-unix
eda_daphne_port: 8001
eda_gunicorn_port: 8000
eda_gunicorn_workers: '{{ ansible_processor_vcpus | default(4) | int * 2 + 1 }}'
eda_podman_mounts:
  - type: bind
    source: '{{ _ca_tls_dir }}/extracted'
    target: /etc/pki/ca-trust/extracted
    relabel: z
eda_workers: 2
eda_workers_range: '{{ range(1, eda_workers | int + 1, 1) | list }}'
eda_activation_workers: 2
eda_activation_workers_range: '{{ range(1, eda_workers | int + 1, 1) | list }}'
eda_max_running_activations: 12
eda_registry_credential: 'Decision Environment Container Registry'
eda_safe_plugins: []
eda_debug: false
eda_type: hybrid
eda_extra_settings: []

# the prefix path for the event stream urls of type webhook
# this should be a large random string to prevent guessing, like for example an uuid
eda_event_stream_prefix_path: "/eda-event-streams"

### database
eda_pg_username: eda
eda_pg_database: eda
eda_pg_port: 5432
eda_pg_sslmode: prefer

### redis
eda_redis_disable_tls: false
eda_redis_queue_db: 3
eda_redis_port: 6379
eda_redis_username: eda
eda_pg_cert_auth: false

### nginx
eda_nginx_conf_dir: '{{ aap_volumes_dir }}/eda/nginx/etc'
eda_nginx_disable_https: false
eda_nginx_disable_hsts: false
eda_nginx_hsts_max_age: 63072000
eda_nginx_http_port: 8082
eda_nginx_https_port: 8445
eda_nginx_https_protocols:
  - TLSv1.2
  - TLSv1.3
eda_nginx_client_max_body_size: 1m
eda_nginx_user_headers: []

### TLS CA
ca_trust_bundle: /etc/pki/tls/certs/ca-bundle.crt
...
