---
- name: Ensure cramfs is unavailable and ensure permissions on /etc/ssh/sshd_config are configured
  hosts: all
  gather_facts: no
  tasks:

    ########################
    # Disable cramfs module 
    ########################

    - name: Check if cramfs module is available
      command: modinfo cramfs
      register: cramfs_modinfo
      ignore_errors: true
      changed_when: false

    - name: cramfs not available, considered compliant
      when: cramfs_modinfo.rc != 0
      debug:
        msg: "cramfs module not available — COMPLIANT"

    - block:
        - name: Check if cramfs is loaded
          command: lsmod
          register: cramfs_lsmod
          changed_when: false

        - name: Check modprobe.d for cramfs deny rules
          shell: grep cramfs /etc/modprobe.d/* || true
          register: cramfs_config
          changed_when: false

        - name: Determine cramfs compliance
          set_fact:
            cramfs_non_compliant: >-
              {{ 'cramfs' in cramfs_lsmod.stdout or
                 'install cramfs /bin/false' not in cramfs_config.stdout or
                 'blacklist cramfs' not in cramfs_config.stdout }}

        - name: Print cramfs compliance result
          debug:
            msg: >-
              cramfs is {{
                'NON-COMPLIANT (module loaded or not properly deny-listed)'
                if cramfs_non_compliant else
                'COMPLIANT (module disabled and deny-listed)'
              }}

        - name: Fail if cramfs is non-compliant
          fail:
            msg: "NON-COMPLIANT: cramfs module is loaded or not properly deny-listed in /etc/modprobe.d/*"
          when: cramfs_non_compliant

      when: cramfs_modinfo.rc == 0

    ########################
    # SSH config file check 
    ########################

    - name: Check /etc/ssh/sshd_config permissions
      stat:
        path: /etc/ssh/sshd_config
      register: sshd_config_stat

    - name: Set result for /etc/ssh/sshd_config
      set_fact:
        sshd_config_compliant: >-
          {{
            (
              (sshd_config_stat.stat.mode | int(base=8)) <= 0o600 and
              sshd_config_stat.stat.pw_name == 'root' and
              sshd_config_stat.stat.gr_name == 'root'
            )
            | ternary('COMPLIANT', 'NON-COMPLIANT')
          }}

    - name: Print compliance result for /etc/ssh/sshd_config
      debug:
        msg: "/etc/ssh/sshd_config — {{ sshd_config_compliant | ternary('COMPLIANT', 'NON-COMPLIANT') }}"


    - name: Fail if non-compliant for /etc/ssh/sshd_config
      fail:
        msg: "/etc/ssh/sshd_config is NON-COMPLIANT."
      when: not sshd_config_compliant
