---
### container
container_log_driver: journald

### common
aap_volumes_dir: '{{ ansible_user_dir }}/aap'

### receptor
receptor_conf_dir: "{{ aap_volumes_dir }}/receptor/etc"
receptor_log_level: info
receptor_peers: []
receptor_port: 27199
receptor_protocol: tcp
receptor_type: execution
receptor_firewall_zone: public
receptor_disable_signing: false
receptor_disable_tls: false
receptor_mintls13: false

### controller
controller_data_dir: '{{ aap_volumes_dir }}/controller/data'

### TLS CA
ca_trust_bundle: /etc/pki/tls/certs/ca-bundle.crt
...
