---
# https://github.com/marketplace/actions/issues-helper
name: Check inactive

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  close-inactive-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'need info, inactive'
          inactive-day: 7
...
