---
# https://github.com/marketplace/actions/issues-helper
name: Check inactive

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  check-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: check-inactive
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-inactive'
          token: ${{ secrets.GITHUB_TOKEN }}
          inactive-day: 30
          issue-state: open
          exclude-labels: 'backlog, help wanted'
...
