---
- name: Create the receptor container
  containers.podman.podman_container:
    name: receptor
    image: '{{ _receptor_image }}'
    image_volume: ignore
    command: /usr/bin/receptor --config /etc/receptor/receptor.conf
    generate_systemd:
      container_prefix: ''
      path: '{{ ansible_user_dir }}/.config/systemd/user'
      separator: ''
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    volume: '{{ _receptor_volumes }}'
    security_opt: ['label=disable']
    env:
      HOME: '/home/{{ ansible_user_id }}'
      RECEPTORCTL_SOCKET: '/run/receptor/receptor.sock'
      CONTAINER_HOST: 'unix://run/user/{{ ansible_user_uid }}/podman/podman.sock'
    label: '{{ _autoupdate_label }}'
    state: created
    recreate: '{{ __containers_recreate | default(false) }}'
  notify: Restart receptor
...
