---
- name: Manage receptor firewalld port
  ansible.posix.firewalld:
    port: '{{ receptor_port }}/{{ receptor_protocol }}'
    permanent: true
    state: '{{ __firewalld_state }}'
    immediate: true
    zone: '{{ receptor_firewall_zone }}'
  become: true
  when:
    - ansible_facts.services.get('firewalld.service', {}) | length
    - ansible_facts.services['firewalld.service']['status'] == 'enabled'
...
