---
- name: Set receptor facts
  ansible.builtin.include_tasks: facts.yml

- name: Configure receptor
  ansible.builtin.include_tasks: config.yml

- name: Create podman volumes
  ansible.builtin.include_tasks: volumes.yml
  vars:
    __volume_state: present

- name: Configure TLS
  ansible.builtin.include_tasks: tls.yml
  when: not receptor_disable_tls | bool

- name: Configure signing
  ansible.builtin.include_tasks: signing.yml
  when: not receptor_disable_signing | bool

- name: Handle container image update
  ansible.builtin.include_tasks: update.yml

- name: Configure containers
  ansible.builtin.include_tasks: containers.yml

- name: Ensure receptor container is enabled and started
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_enabled: true
    __systemd_state: started

- name: Add firewalld rules
  ansible.builtin.include_tasks: firewalld.yml
  vars:
    __firewalld_state: enabled
  when: groups['automationcontroller'] | length > 1 or groups.get('execution_nodes', []) | length > 0
...
