---
- name: Generate RSA key pair
  when:
    - receptor_signing_private_key is not defined
    - receptor_signing_public_key is not defined
  run_once: true
  block:
    - name: Install python-cryptography
      ansible.builtin.package:
        name: python3-cryptography
      become: true
      when:
        - not ostree | bool
        - _receptor_type in ['control', 'hybrid']

    - name: Generate a RSA private key
      community.crypto.openssl_privatekey:
        path: '{{ receptor_conf_dir }}/signing_private.pem'
        type: RSA
        format: pkcs1
        mode: '0400'
      when: _receptor_type in ['control', 'hybrid']

    - name: Generate a RSA public key
      community.crypto.openssl_publickey:
        path: '{{ receptor_conf_dir }}/signing_public.pem'
        privatekey_path: '{{ receptor_conf_dir }}/signing_private.pem'
        format: PEM
        mode: '0640'
      when: _receptor_type in ['control', 'hybrid']

    - name: Copy signing RSA keys to other nodes
      block:
        - name: Create local temporary directory
          ansible.builtin.tempfile:
            state: directory
          register: _signing_temp
          delegate_to: localhost

        - name: Fetch files locally
          ansible.builtin.fetch:
            src: '{{ receptor_conf_dir }}/signing_{{ item }}.pem'
            dest: '{{ _signing_temp.path }}/signing_{{ item }}.pem'
            flat: true
          loop:
            - private
            - public

        - name: Copy RSA public key
          ansible.builtin.copy:
            src: '{{ _signing_temp.path }}/signing_public.pem'
            dest: '{{ receptor_conf_dir }}/signing_public.pem'
            mode: '0640'
          run_once: false
          when: _receptor_type in ['control', 'execution', 'hybrid']
          notify: Restart receptor

        - name: Copy RSA private key
          ansible.builtin.copy:
            src: '{{ _signing_temp.path }}/signing_private.pem'
            dest: '{{ receptor_conf_dir }}/signing_private.pem'
            mode: '0400'
          run_once: false
          when: _receptor_type in ['control', 'hybrid']
          notify: Restart receptor
      always:
        - name: Remove local temporary directory
          ansible.builtin.file:
            path: '{{ _signing_temp.path }}'
            state: absent
          delegate_to: localhost

- name: Import RSA key pair
  when:
    - receptor_signing_private_key is defined
    - receptor_signing_public_key is defined
  block:
    - name: Copy receptor signing RSA public key
      ansible.builtin.copy:
        src: '{{ receptor_signing_public_key }}'
        dest: '{{ receptor_conf_dir }}/signing_public.pem'
        mode: '0640'
        remote_src: '{{ receptor_signing_remote | default(false) }}'
      when: _receptor_type in ['control', 'execution', 'hybrid']
      notify: Restart receptor

    - name: Copy receptor signing RSA private key
      ansible.builtin.copy:
        src: '{{ receptor_signing_private_key }}'
        dest: '{{ receptor_conf_dir }}/signing_private.pem'
        mode: '0400'
        remote_src: '{{ receptor_signing_remote | default(false) }}'
      when: _receptor_type in ['control', 'hybrid']
      notify: Restart receptor
...
