---
- name: Generate TLS certificate and key
  when:
    - receptor_tls_cert is not defined
    - receptor_tls_key is not defined
  block:
    - name: Install python-cryptography
      ansible.builtin.package:
        name: python3-cryptography
      become: true
      when: not ostree | bool

    - name: Check the current receptor private key
      ansible.builtin.stat:
        path: '{{ receptor_conf_dir }}/receptor.key'
      register: _receptor_tls_key

    - name: Generate a private key
      community.crypto.openssl_privatekey:
        path: '{{ receptor_conf_dir }}/receptor.key'
        mode: '0400'
      when: not _receptor_tls_key.stat.exists | bool

    - name: Check the current receptor certificate
      ansible.builtin.stat:
        path: '{{ receptor_conf_dir }}/receptor.crt'
      register: _receptor_tls_cert

    - name: Create the receptor TLS certificate
      when: not _receptor_tls_cert.stat.exists | bool
      block:
        - name: Generate a certificate signing request
          community.crypto.openssl_csr_pipe:
            common_name: '{{ _receptor_hostname }}'
            country_name: 'US'
            locality_name: 'Raleigh'
            organization_name: 'Red Hat'
            organizational_unit_name: 'Ansible'
            state_or_province_name: 'North Carolina'
            subject_alt_name: '{{ [_receptor_hostname | ansible.containerized_installer.subject_alt_name, _receptor_oid] | union(_receptor_ips) }}'
            privatekey_path: '{{ receptor_conf_dir }}/receptor.key'
          vars:
            _receptor_oid: 'otherName:1.3.6.1.4.1.2312.19.1;UTF8:{{ _receptor_hostname }}'
          register: _receptor_tls_csr

        - name: Generate a self signed x509 certificate
          community.crypto.x509_certificate:
            path: '{{ receptor_conf_dir }}/receptor.crt'
            csr_content: '{{ _receptor_tls_csr.csr }}'
            privatekey_path: '{{ receptor_conf_dir }}/receptor.key'
            provider: ownca
            ownca_path: '{{ _ca_tls_dir }}/ca.cert'
            ownca_privatekey_path: '{{ _ca_tls_dir }}/ca.key'
            ownca_privatekey_passphrase: '{{ ca_tls_key_passphrase | default(omit) }}'
            mode: '0640'

- name: Import TLS certificate and key
  when:
    - receptor_tls_cert is defined
    - receptor_tls_key is defined
  block:
    - name: Copy receptor TLS certificate
      ansible.builtin.copy:
        src: '{{ receptor_tls_cert }}'
        dest: '{{ receptor_conf_dir }}/receptor.crt'
        mode: '0640'
        remote_src: '{{ receptor_tls_remote | default(false) }}'
      notify: Restart receptor

    - name: Copy receptor TLS key
      ansible.builtin.copy:
        src: '{{ receptor_tls_key }}'
        dest: '{{ receptor_conf_dir }}/receptor.key'
        mode: '0400'
        remote_src: '{{ receptor_tls_remote | default(false) }}'
      notify: Restart receptor
...
