---
- name: Ensure systemd unit is disabled and stopped
  ansible.builtin.systemd:
    name: receptor.service
    state: stopped
    enabled: false
    scope: user
  failed_when: false

- name: Reset receptor systemd unit
  ansible.builtin.command: systemctl --user reset-failed receptor.service # noqa: command-instead-of-module
  changed_when: false
  failed_when: false

- name: Delete the container
  containers.podman.podman_container:
    name: receptor
    state: absent

- name: Delete the systemd unit file
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/systemd/user/receptor.service'
    state: absent

- name: Remove podman volumes
  ansible.builtin.include_tasks: volumes.yml
  vars:
    __volume_state: absent

- name: Delete the directory
  ansible.builtin.file:
    path: '{{ aap_volumes_dir }}/{{ item }}'
    state: absent
  loop:
    - controller
    - receptor

- name: Delete firewalld rules
  ansible.builtin.include_tasks: firewalld.yml
  vars:
    __firewalld_state: disabled
...
