---
- name: Manage the receptor volumes
  containers.podman.podman_volume:
    name: '{{ item }}'
    state: '{{ __volume_state }}'
  loop:
    - receptor_run
    - receptor_runner
    - receptor_home
    - receptor_data
...
