---
- name: Get eda version
  ansible.builtin.include_tasks: version.yml

- name: Set automation eda facts
  ansible.builtin.include_tasks: facts.yml

- name: Configure postgresql
  ansible.builtin.include_tasks: postgresql.yml
  args:
    apply:
      run_once: true
  when: groups.get('database', []) | length == 1 or postgresql_admin_password is defined

- name: Configure automation EDA
  ansible.builtin.include_tasks: config.yml

- name: Configure TLS for nginx
  ansible.builtin.include_tasks: tls.yml
  when: not eda_nginx_disable_https | bool

- name: Configure TLS for redis
  ansible.builtin.include_tasks: tls_redis.yml
  when:
    - groups['automationeda'] | length > 1
    - not eda_redis_disable_tls | bool

- name: Configure TLS for postgresql
  ansible.builtin.include_tasks: tls_postgresql.yml
  when: eda_pg_cert_auth | bool

- name: Configure nginx
  ansible.builtin.include_tasks: nginx.yml

- name: Configure podman secrets
  ansible.builtin.include_tasks: secrets.yml

- name: Create podman volumes
  ansible.builtin.include_tasks: volumes.yml
  vars:
    __volume_state: present

- name: Handle container image update
  ansible.builtin.include_tasks: update.yml

- name: Configure containers
  ansible.builtin.include_tasks: containers.yml
  vars:
    __containers_recreate: '{{ __eda_recreate }}'

- name: Initialize data
  ansible.builtin.include_tasks: init.yml

- name: Ensure automation eda containers are enabled and started
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_enabled: true
    __systemd_state: started

- name: Add firewalld rules
  ansible.builtin.include_tasks: firewalld.yml
  vars:
    __firewalld_state: enabled

- name: Add decision environments
  ansible.builtin.include_tasks: decision_environment.yml
  args:
    apply:
      run_once: true
  when: eda_type in ['api', 'hybrid']
...
