---
- name: Install python-psycopg2
  ansible.builtin.package:
    name: python3-psycopg2
  become: true
  when: not ostree | bool

- name: Wait for postgresql to be ready
  community.postgresql.postgresql_ping:
    login_host: '{{ eda_pg_host }}'
    login_port: '{{ eda_pg_port }}'
    login_user: '{{ postgresql_admin_username | default("postgres") }}'
    login_password: '{{ postgresql_admin_password | default(omit) }}'
    login_db: '{{ postgresql_admin_database | default("postgres") }}'
    login_unix_socket: '{{ eda_pg_socket | default(omit) }}'
  register: _ping
  retries: 30
  delay: 10
  until:
    - _ping.is_available is defined
    - _ping.is_available | bool

- name: Create the automation eda postgresql user
  community.postgresql.postgresql_user:
    name: '{{ eda_pg_username }}'
    password: '{{ eda_pg_password | default(omit) }}'
    login_host: '{{ eda_pg_host }}'
    login_port: '{{ eda_pg_port }}'
    login_user: '{{ postgresql_admin_username | default("postgres") }}'
    login_password: '{{ postgresql_admin_password | default(omit) }}'
    login_db: '{{ postgresql_admin_database | default("postgres") }}'
    login_unix_socket: '{{ eda_pg_socket | default(omit) }}'

- name: Grant the automation eda role to postgresql admin user
  community.postgresql.postgresql_membership:
    source_role: '{{ eda_pg_username }}'
    target_role: '{{ postgresql_admin_username | default("postgres") }}'
    login_host: '{{ eda_pg_host }}'
    login_port: '{{ eda_pg_port }}'
    login_user: '{{ postgresql_admin_username | default("postgres") }}'
    login_password: '{{ postgresql_admin_password | default(omit) }}'
    login_db: '{{ postgresql_admin_database | default("postgres") }}'
    login_unix_socket: '{{ eda_pg_socket | default(omit) }}'

- name: Create the automation eda postgresql database
  community.postgresql.postgresql_db:
    name: '{{ eda_pg_database }}'
    owner: '{{ eda_pg_username }}'
    login_host: '{{ eda_pg_host }}'
    login_port: '{{ eda_pg_port }}'
    login_user: '{{ postgresql_admin_username | default("postgres") }}'
    login_password: '{{ postgresql_admin_password | default(omit) }}'
    login_unix_socket: '{{ eda_pg_socket | default(omit) }}'
    maintenance_db: '{{ postgresql_admin_database | default("postgres") }}'
...
