---
- name: Set automation eda facts
  ansible.builtin.include_tasks: facts.yml

- name: Set podman version facts
  ansible.builtin.include_role:
    name: common
    tasks_from: podman_facts.yml

- name: Set eda redis hostname
  ansible.builtin.set_fact:
    _eda_redis_hostname: '{{ hostvars[groups["automationgateway"][0]]["_gateway_redis_hostname"] }}'
  when: groups['automationeda'] | length > 1

- name: Stop automation eda systemd services
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_state: stopped

- name: Unarchive the automation eda data
  ansible.builtin.unarchive:
    src: '{{ hostvars["localhost"]["_backup_dir"] }}/eda_{{ inventory_hostname }}.tar.gz'
    dest: '{{ ansible_user_dir }}'
    exclude:
      - 'aap/tls'
      - '.local/share/containers/storage/secrets/'
      - 'aap/eda/nginx/etc/redirect-page.html'
      - 'aap/eda/etc/'
      - 'aap/eda/etc/eda.key'
      - 'aap/eda/etc/eda.cert'

- name: Set automation eda controller secret facts
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_secrets.yml
  vars:
    backup_file: '{{ hostvars["localhost"]["_backup_dir"] }}/eda_{{ inventory_hostname }}.tar.gz'

- name: Update the relevant eda secrets
  containers.podman.podman_secret:
    name: "{{ item }}"
    data: "{{ lookup('ansible.builtin.vars', '__old_' + item) | b64decode }}"
    skip_existing: '{{ _podman_idempotence | ternary(omit, true) }}'
    force: '{{ _podman_idempotence | ternary(omit, true) }}'
  loop:
    - eda_secret_key

- name: Override redis database and host when using cluster
  ansible.builtin.set_fact:
    _redis_cluster_db: 0
    _redis_cluster_host: '{{ hostvars[groups["redis"][0]]["_redis_hostname"] }}'
  when:
    - redis_mode | default('cluster') == 'cluster'
    - groups['automationeda'] | length > 1

- name: Invalid redis cache
  ansible.builtin.include_role:
    name: redis
    tasks_from: flush.yml
  vars:
    __redis_databases:
      - '{{ _redis_cluster_db | default(eda_redis_queue_db) }}'
    __redis_host: '{{ _redis_cluster_host | default(_eda_redis_hostname) | default(omit) }}'
    __redis_port: '{{ eda_redis_port }}'
    __redis_cert: '{{ eda_conf_dir }}/redis.cert'
    __redis_key: '{{ eda_conf_dir }}/redis.key'
    redis_unix_socket: '{{ groups["automationeda"] | length == 1 | bool }}'
    redis_disable_tls: '{{ eda_redis_disable_tls }}'

- name: Reconfigure containers
  ansible.builtin.include_tasks: containers.yml
  vars:
    __containers_recreate: true

- name: Create postgresql CLI aliases
  ansible.builtin.include_role:
    name: postgresql
    tasks_from: cli.yml
  vars:
    _postgresql_socket: '{{ eda_pg_socket | default("") }}'
    _postgresql_cert_auth: '{{ eda_pg_cert_auth }}'
    _postgresql_src_dir: '{{ eda_conf_dir }}'
    _postgresql_dest_dir: /etc/eda

- name: Add postgresql TLS environment variable for certificate authentication
  ansible.builtin.set_fact:
    _eda_pg_restore:
      PGSSLCERT: /etc/eda/postgresql.cert
      PGSSLKEY: /etc/eda/postgresql.key
      PGSSLROOTCERT: '{{ ca_trust_bundle }}'
  when: eda_pg_cert_auth | bool

- name: Grant createdb role to the automation eda postgresql user
  community.postgresql.postgresql_user:
    name: '{{ eda_pg_username }}'
    role_attr_flags: CREATEDB
    login_host: '{{ eda_pg_host }}'
    login_port: '{{ eda_pg_port }}'
    login_user: '{{ postgresql_admin_username | default("postgres") }}'
    login_password: '{{ postgresql_admin_password | default(omit) }}'
    login_db: '{{ postgresql_admin_database | default("postgres") }}'
    login_unix_socket: '{{ eda_pg_socket | default(omit) }}'
  run_once: true
  when: groups.get('database', []) | length == 1 or postgresql_admin_password is defined

- name: Restore the automation eda postgresql database
  community.postgresql.postgresql_db:
    name: template1
    login_host: '{{ eda_pg_host }}'
    login_port: '{{ eda_pg_port }}'
    login_user: '{{ eda_pg_username }}'
    login_password: '{{ eda_pg_password | default(omit) }}'
    login_unix_socket: '{{ eda_pg_socket | default(omit) }}'
    ssl_mode: '{{ eda_pg_sslmode }}'
    target: '{{ ansible_user_dir }}/aap/backups/{{ eda_pg_database }}.pgc'
    target_opts: '--create --clean --if-exists'
    state: restore
  environment: '{{ _eda_pg_restore | default({}) }}'
  run_once: true

- name: Revoke createdb role to the automation eda postgresql user
  community.postgresql.postgresql_user:
    name: '{{ eda_pg_username }}'
    role_attr_flags: NOCREATEDB
    login_host: '{{ eda_pg_host }}'
    login_port: '{{ eda_pg_port }}'
    login_user: '{{ postgresql_admin_username | default("postgres") }}'
    login_password: '{{ postgresql_admin_password | default(omit) }}'
    login_db: '{{ postgresql_admin_database | default("postgres") }}'
    login_unix_socket: '{{ eda_pg_socket | default(omit) }}'
  run_once: true
  when: groups.get('database', []) | length == 1 or postgresql_admin_password is defined

- name: Start automation eda systemd services
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_state: started

- name: Add decision environments
  ansible.builtin.include_tasks: decision_environment.yml
  args:
    apply:
      run_once: true
  when: eda_type in ['api', 'hybrid']
...
