---
- name: Import postgresql TLS certificate and key
  when:
    - eda_pg_tls_cert is defined
    - eda_pg_tls_key is defined
  block:
    - name: Copy postgresql TLS certificate
      ansible.builtin.copy:
        src: '{{ eda_pg_tls_cert }}'
        dest: '{{ eda_conf_dir }}/postgresql.cert'
        mode: '0640'
        remote_src: '{{ eda_tls_remote | default(false) }}'
      notify:
        - Restart eda api
        - Restart eda daphne
        - Restart eda workers
        - Restart eda activation workers
        - Restart eda scheduler

    - name: Copy postgresql TLS key
      ansible.builtin.copy:
        src: '{{ eda_pg_tls_key }}'
        dest: '{{ eda_conf_dir }}/postgresql.key'
        mode: '0400'
        remote_src: '{{ eda_tls_remote | default(false) }}'
      notify:
        - Restart eda api
        - Restart eda daphne
        - Restart eda workers
        - Restart eda activation workers
        - Restart eda scheduler
...
