---
- name: Set facts for containers
  ansible.builtin.set_fact:
    __containers:
      - automation-eda-api
      - automation-eda-daphne
      - automation-eda-scheduler
      - automation-eda-web

- name: Add eda workers to containers list
  ansible.builtin.set_fact:
    __containers: '{{ __containers | union(["automation-eda-worker-" + item | string]) }}'
  loop: '{{ eda_workers_range }}'

- name: Add eda activation workers containers list
  ansible.builtin.set_fact:
    __containers: '{{ __containers | union(["automation-eda-activation-worker-" + item | string]) }}'
  loop: '{{ eda_activation_workers_range }}'

- name: Get eda container information
  containers.podman.podman_container_info:
    name: '{{ __containers }}'
  register: _eda_container_info

- name: Get eda image information
  containers.podman.podman_image_info:
    name:
      - '{{ _eda_image }}'
      - '{{ _eda_web_image }}'
  register: _eda_image_info

- name: Set eda update fact
  ansible.builtin.set_fact:
    _eda_image_update: '{{ _eda_before | difference(_eda_after) | length > 0 }}'
  vars:
    _eda_before: '{{ _eda_container_info.containers | map(attribute="Image") | unique }}'
    _eda_after: '{{ _eda_image_info.images | map(attribute="Id") | unique }}'

- name: Stop eda service on update
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_state: stopped
  when: _eda_image_update | bool
...
