---
galaxy_info:
  role_name: "collection"
  author: "Inderpal Tiwana"
  description: "An Ansible Role to update, or destroy Automation Hub Collections."
  company: "Red Hat"

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker
  license: "GPLv3+"

  min_ansible_version: "2.9"

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.

  # github_branch:

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  platforms:
    - name: "EL"
      versions:
        - "all"

  galaxy_tags:
    - "automationhub"
    - "galaxy"
    - "configuration"
    - "collection"
    - "sync"

dependencies: []
# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
...
