---
- name: Wait for the Web port to be reachable
  ansible.builtin.wait_for:
    port: '{{ _controller_port }}'

- name: Wait for the Controller API to te ready
  ansible.builtin.uri:
    url: '{{ _controller_url }}/api/v2/ping/'
    validate_certs: true
    ca_path: '{{ _ca_tls_dir }}/extracted/pem/tls-ca-bundle.pem'

- name: Upload the Automation Controller subscription
  block:
    - name: Create a tmp file for the license
      ansible.builtin.tempfile:
        state: file
      register: _controller_license_file

    - name: Copy the license file
      ansible.builtin.copy:
        src: '{{ controller_license_file }}'
        dest: '{{ _controller_license_file.path }}'
        mode: '0400'

    - name: Add Automation Controller subscription
      ansible.controller.license:
        controller_host: '{{ _controller_url }}'
        controller_username: '{{ controller_admin_user }}'
        controller_password: '{{ controller_admin_password }}'
        manifest: '{{ _controller_license_file.path }}'
        force: true
        validate_certs: true
      environment:
        SSL_CERT_FILE: '{{ _ca_tls_dir }}/extracted/pem/tls-ca-bundle.pem'
  always:
    - name: Delete the tmp file
      ansible.builtin.file:
        path: '{{ _controller_license_file.path }}'
        state: absent
...
