---
- name: Manage remote postinstall configuration
  when:
    - controller_postinstall_repo_url is defined
    - controller_postinstall_repo_url | length
  delegate_to: localhost
  block:
    - name: Install the git binary
      ansible.builtin.package:
        name: git-core
      become: true
      when: not ostree | bool

    - name: Clone the postinstall config repository
      ansible.builtin.git:
        repo: '{{ controller_postinstall_repo_url }}'
        dest: '{{ controller_postinstall_dir }}'
        version: '{{ controller_postinstall_repo_ref }}'
        force: true

- name: Include vars for automation controller
  ansible.builtin.include_vars:
    dir: '{{ controller_postinstall_dir }}'
    extensions:
      - yml
      - yaml
    ignore_files: '{{ controller_postinstall_ignore_files }}'
    ignore_unknown_extensions: true

- name: Execute automation controller resource configuration
  ansible.builtin.include_role:
    name: infra.controller_configuration.dispatch
    apply:
      environment:
        SSL_CERT_FILE: '{{ _ca_tls_dir }}/extracted/pem/tls-ca-bundle.pem'
  run_once: true
  vars:
    controller_hostname: '{{ _controller_url }}'
    controller_username: '{{ controller_admin_user }}'
    controller_password: '{{ controller_admin_password }}'
    controller_validate_certs: true
    controller_configuration_async_delay: '{{ controller_postinstall_async_delay }}'
    controller_configuration_async_retries: '{{ controller_postinstall_async_retries }}'
...
