---
- name: Generate TLS certificate and key
  when:
    - controller_tls_cert is not defined
    - controller_tls_key is not defined
  block:
    - name: Install python-cryptography
      ansible.builtin.package:
        name: python3-cryptography
      become: true
      when: not ostree | bool

    - name: Check the current controller private key
      ansible.builtin.stat:
        path: '{{ controller_conf_dir }}/tower.key'
      register: _controller_tls_key

    - name: Generate a private key
      community.crypto.openssl_privatekey:
        path: '{{ controller_conf_dir }}/tower.key'
        mode: '0400'
      when: not _controller_tls_key.stat.exists | bool

    - name: Check the current controller certificate
      ansible.builtin.stat:
        path: '{{ controller_conf_dir }}/tower.cert'
      register: _controller_tls_cert

    - name: Create the controller TLS certificate
      when: not _controller_tls_cert.stat.exists | bool
      block:
        - name: Generate a certificate signing request
          community.crypto.openssl_csr_pipe:
            common_name: '{{ _controller_hostname }}'
            country_name: 'US'
            locality_name: 'Raleigh'
            organization_name: 'Red Hat'
            organizational_unit_name: 'Ansible'
            state_or_province_name: 'North Carolina'
            subject_alt_name: '{{ [_controller_hostname | ansible.containerized_installer.subject_alt_name] | union(_controller_ips) }}'
            privatekey_path: '{{ controller_conf_dir }}/tower.key'
          register: _controller_tls_csr

        - name: Generate a self signed x509 certificate
          community.crypto.x509_certificate:
            path: '{{ controller_conf_dir }}/tower.cert'
            csr_content: '{{ _controller_tls_csr.csr }}'
            privatekey_path: '{{ controller_conf_dir }}/tower.key'
            provider: ownca
            ownca_path: '{{ _ca_tls_dir }}/ca.cert'
            ownca_privatekey_path: '{{ _ca_tls_dir }}/ca.key'
            ownca_privatekey_passphrase: '{{ ca_tls_key_passphrase | default(omit) }}'
            mode: '0640'

- name: Import TLS certificate and key
  when:
    - controller_tls_cert is defined
    - controller_tls_key is defined
  block:
    - name: Copy controller TLS certificate
      ansible.builtin.copy:
        src: '{{ controller_tls_cert }}'
        dest: '{{ controller_conf_dir }}/tower.cert'
        mode: '0640'
        remote_src: '{{ controller_tls_remote | default(false) }}'
      notify: Restart controller web

    - name: Copy controller TLS key
      ansible.builtin.copy:
        src: '{{ controller_tls_key }}'
        dest: '{{ controller_conf_dir }}/tower.key'
        mode: '0400'
        remote_src: '{{ controller_tls_remote | default(false) }}'
      notify: Restart controller web
...
