---
- name: Import postgresql TLS certificate and key
  when:
    - controller_pg_tls_cert is defined
    - controller_pg_tls_key is defined
  block:
    - name: Copy postgresql TLS certificate
      ansible.builtin.copy:
        src: '{{ controller_pg_tls_cert }}'
        dest: '{{ controller_conf_dir }}/postgresql.cert'
        mode: '0640'
        remote_src: '{{ controller_tls_remote | default(false) }}'
      notify:
        - Restart controller rsyslog
        - Restart controller task
        - Restart controller web

    - name: Copy postgresql TLS key
      ansible.builtin.copy:
        src: '{{ controller_pg_tls_key }}'
        dest: '{{ controller_conf_dir }}/postgresql.key'
        mode: '0400'
        remote_src: '{{ controller_tls_remote | default(false) }}'
      notify:
        - Restart controller rsyslog
        - Restart controller task
        - Restart controller web
...
