---
- name: Set facts for containers
  ansible.builtin.set_fact:
    __containers:
      - automation-controller-rsyslog
      - automation-controller-task
      - automation-controller-web

- name: Set facts for systemd services and containers
  ansible.builtin.set_fact:
    __services: '{{ __containers | product(["service"]) | map("join", ".") }}'

- name: Set controller port list
  ansible.builtin.set_fact:
    _controller_ports: ['{{ controller_nginx_http_port }}']

- name: Add https port to controller port list
  ansible.builtin.set_fact:
    _controller_ports: '{{ _controller_ports | union([controller_nginx_https_port]) }}'
  when: not controller_nginx_disable_https | bool

- name: Ensure systemd units are disabled and stopped
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: stopped
    enabled: false
    scope: user
  failed_when: false
  loop: '{{ __services }}'

- name: Delete the containers
  containers.podman.podman_container:
    name: '{{ item }}'
    state: absent
  loop: '{{ __containers }}'

- name: Delete the systemd unit files
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/systemd/user/{{ item }}'
    state: absent
  loop: '{{ __services }}'

- name: Delete podman volumes
  ansible.builtin.include_tasks: volumes.yml
  vars:
    __volume_state: absent

- name: Delete the controller secrets
  containers.podman.podman_secret:
    name: '{{ item }}'
    state: absent
  loop:
    - controller_channels
    - controller_postgres
    - controller_resource_server
    - controller_secret_key

- name: Delete the directories/files
  ansible.builtin.file:
    path: '{{ aap_volumes_dir }}/controller'
    state: absent

- name: Delete firewalld rules
  ansible.builtin.include_tasks: firewalld.yml
  vars:
    __firewalld_state: disabled
...
