---
- name: Get controller container information
  containers.podman.podman_container_info:
    name:
      - automation-controller-rsyslog
      - automation-controller-task
      - automation-controller-web
  register: _controller_container_info

- name: Get controller image information
  containers.podman.podman_image_info:
    name: '{{ _controller_image }}'
  register: _controller_image_info

- name: Set controller update fact
  ansible.builtin.set_fact:
    _controller_image_update: '{{ _controller_before | difference(_controller_after) | length > 0 }}'
  vars:
    _controller_before: '{{ _controller_container_info.containers | map(attribute="Image") | unique }}'
    _controller_after: '{{ _controller_image_info.images | map(attribute="Id") | unique }}'

- name: Stop controller service on update
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_state: stopped
  when: _controller_image_update | bool
...
