---
- name: Get automation controller version
  containers.podman.podman_container:
    name: automation-controller-version
    image: '{{ _controller_image }}'
    command: 'awx-manage version'
    detach: false
    rm: true
    env:
      AWX_SETTINGS_FILE: '/dev/null'
      SKIP_PG_VERSION_CHECK: true
  changed_when: false
  register: _controller_version

- name: Set automation controller version fact
  ansible.builtin.set_fact:
    __controller_version: '{{ _controller_version.stdout | trim }}'
...
