---
### container
container_log_driver: journald

### common
aap_volumes_dir: '{{ ansible_user_dir }}/aap'

### controller
controller_admin_user: admin
controller_admin_email: admin@example.com
controller_firewall_zone: public
controller_data_dir: '{{ aap_volumes_dir }}/controller/data'
controller_conf_dir: '{{ aap_volumes_dir }}/controller/etc'
controller_container_label: 'level:s0:c100,c200'
controller_container_requires:
  - redis-unix
controller_daphne_port: 8051
controller_uwsgi_port: 8050
controller_uwsgi_processes: '{{ ansible_processor_vcpus | default(4) | int * 2 + 1 }}'
controller_uwsgi_listen_queue_size: 2048
controller_event_workers: 4
controller_precreate_partition_hours: 3
controller_percent_memory_capacity: 1.0
controller_extra_settings: []

### database
controller_pg_username: awx
controller_pg_database: awx
controller_pg_port: 5432
controller_pg_sslmode: prefer
controller_pg_cert_auth: false

### redis
controller_redis_broker_db: 0
controller_redis_cache_db: 1

### postinstall
controller_postinstall_ignore_files: []
controller_postinstall_repo_ref: main
controller_postinstall_async_delay: 1
controller_postinstall_async_retries: 30

### nginx
controller_nginx_conf_dir: '{{ aap_volumes_dir }}/controller/nginx/etc'
controller_nginx_disable_https: false
controller_nginx_disable_hsts: false
controller_nginx_hsts_max_age: 63072000
controller_nginx_http_port: 8080
controller_nginx_https_port: 8443
controller_nginx_https_protocols:
  - TLSv1.2
  - TLSv1.3
controller_nginx_client_max_body_size: 5m
controller_nginx_user_headers: []

### receptor
receptor_conf_dir: "{{ aap_volumes_dir }}/receptor/etc"

### rsyslog
rsyslog_run_dir: '{{ aap_volumes_dir }}/controller/rsyslog/run'

### supervisor
supervisor_run_dir: '{{ aap_volumes_dir }}/controller/supervisor/run'

### TLS CA
ca_trust_bundle: /etc/pki/tls/certs/ca-bundle.crt
...
