collections:
- name: amazon-aws-9.2.0.tar.gz
  version: 9.2.0
- name: ansible-controller-4.6.11.tar.gz
  version: 4.6.11
- name: ansible-eda-2.6.0.tar.gz
  version: 2.6.0
- name: ansible-hub-1.0.0.tar.gz
  version: 1.0.0
- name: ansible-netcommon-7.1.0.tar.gz
  version: 7.1.0
- name: ansible-network-4.0.0.tar.gz
  version: 4.0.0
- name: ansible-platform-2.5.20250326.tar.gz
  version: 2.5.20250326
- name: ansible-posix-1.5.4.tar.gz
  version: 1.5.4
- name: ansible-scm-3.0.0.tar.gz
  version: 3.0.0
- name: ansible-security-3.0.0.tar.gz
  version: 3.0.0
- name: ansible-snmp-3.0.0.tar.gz
  version: 3.0.0
- name: ansible-utils-5.1.2.tar.gz
  version: 5.1.2
- name: ansible-windows-2.7.0.tar.gz
  version: 2.7.0
- name: ansible-yang-3.0.0.tar.gz
  version: 3.0.0
- name: arista-eos-10.0.1.tar.gz
  version: 10.0.1
- name: azure-azcollection-2.5.0.tar.gz
  version: 2.5.0
- name: cisco-asa-6.0.0.tar.gz
  version: 6.0.0
- name: cisco-ios-9.1.1.tar.gz
  version: 9.1.1
- name: cisco-iosxr-10.3.0.tar.gz
  version: 10.3.0
- name: cisco-nxos-9.3.0.tar.gz
  version: 9.3.0
- name: cloud-common-4.0.0.tar.gz
  version: 4.0.0
- name: cloud-terraform-3.0.0.tar.gz
  version: 3.0.0
- name: frr-frr-2.0.2.tar.gz
  version: 2.0.2
- name: ibm-qradar-4.0.0.tar.gz
  version: 4.0.0
- name: junipernetworks-junos-9.1.0.tar.gz
  version: 9.1.0
- name: kubernetes-core-5.0.1.tar.gz
  version: 5.0.1
- name: microsoft-ad-1.8.0.tar.gz
  version: 1.8.0
- name: openvswitch-openvswitch-2.1.1.tar.gz
  version: 2.1.1
- name: redhat-amq_broker-1.3.0.tar.gz
  version: 1.3.0
- name: redhat-amq_streams-1.0.0.tar.gz
  version: 1.0.0
- name: redhat-data_grid-1.3.1.tar.gz
  version: 1.3.1
- name: redhat-eap-1.3.1.tar.gz
  version: 1.3.1
- name: redhat-insights-1.3.0.tar.gz
  version: 1.3.0
- name: redhat-insights_eda-1.2.0.tar.gz
  version: 1.2.0
- name: redhat-jbcs-1.0.1.tar.gz
  version: 1.0.1
- name: redhat-jws-2.0.0.tar.gz
  version: 2.0.0
- name: redhat-openshift-4.0.1.tar.gz
  version: 4.0.1
- name: redhat-openshift_virtualization-1.2.3.tar.gz
  version: 1.2.3
- name: redhat-redhat_csp_download-1.2.2.tar.gz
  version: 1.2.2
- name: redhat-rhbk-2.2.2.tar.gz
  version: 2.2.2
- name: redhat-rhel_idm-1.10.0.tar.gz
  version: 1.10.0
- name: redhat-rhel_system_roles-1.21.1.tar.gz
  version: 1.21.1
- name: redhat-rhv-2.4.2.tar.gz
  version: 2.4.2
- name: redhat-runtimes_common-1.1.3.tar.gz
  version: 1.1.3
- name: redhat-sap_install-1.2.1.tar.gz
  version: 1.2.1
- name: redhat-satellite-3.10.0.tar.gz
  version: 3.10.0
- name: redhat-satellite_operations-1.3.0.tar.gz
  version: 1.3.0
- name: redhat-sso-1.3.0.tar.gz
  version: 1.3.0
- name: sap-sap_operations-1.0.4.tar.gz
  version: 1.0.4
- name: servicenow-itsm-2.6.3.tar.gz
  version: 2.6.3
- name: splunk-es-4.0.0.tar.gz
  version: 4.0.0
- name: trendmicro-deepsec-4.0.0.tar.gz
  version: 4.0.0
- name: vmware-vmware-1.10.1.tar.gz
  version: 1.10.1
- name: vmware-vmware_rest-4.6.0.tar.gz
  version: 4.6.0
- name: vyos-vyos-4.0.2.tar.gz
  version: 4.0.2
