---
- name: Restart automation gateway proxy
  ansible.builtin.systemd:
    name: automation-gateway-proxy.service
    scope: user
    state: restarted

- name: Restart automation gateway
  ansible.builtin.systemd:
    name: automation-gateway.service
    scope: user
    state: restarted
...
