---
- name: Manage remote postinstall configuration
  when:
    - hub_postinstall_repo_url is defined
    - hub_postinstall_repo_url | length
  delegate_to: localhost
  block:
    - name: Install the git binary
      ansible.builtin.package:
        name: git-core
      become: true
      when: not ostree | bool

    - name: Clone the postinstall config repository
      ansible.builtin.git:
        repo: '{{ hub_postinstall_repo_url }}'
        dest: '{{ hub_postinstall_dir }}'
        version: '{{ hub_postinstall_repo_ref }}'
        force: true

- name: Include vars for automation hub
  ansible.builtin.include_vars:
    dir: '{{ hub_postinstall_dir }}'
    extensions:
      - yml
      - yaml
    ignore_files: '{{ hub_postinstall_ignore_files }}'
    ignore_unknown_extensions: true

- name: Execute automation hub resource configuration
  ansible.builtin.include_role:
    name: infra.ah_configuration.dispatch
    apply:
      environment:
        SSL_CERT_FILE: '{{ _ca_tls_dir }}/extracted/pem/tls-ca-bundle.pem'
  run_once: true
  vars:
    ah_host: '{{ hostvars[groups["automationgateway"][0]]["_gateway_proxy_url"] }}'
    ah_username: admin
    ah_password: '{{ hub_admin_password }}'
    ah_validate_certs: true
    ah_configuration_async_delay: '{{ hub_postinstall_async_delay }}'
    ah_configuration_async_retries: '{{ hub_postinstall_async_retries }}'
...
