---
- name: Get pulpcore version from container image
  containers.podman.podman_container:
    name: pulpcore-version
    image: '{{ _hub_image }}'
    entrypoint: ''
    command: ["python3", "-c", "{{ __py_args }}"]
    detach: false
    rm: true
  changed_when: false
  vars:
    __py_args: 'from importlib.metadata import version; print(version("pulpcore"))'
  register: _pulpcore_version

- name: Set pulpcore version fact
  ansible.builtin.set_fact:
    __pulpcore_version: '{{ _pulpcore_version.stdout | trim }}'
...
