---
- name: Manage the Automation Hub data volume
  containers.podman.podman_volume:
    name: hub_data
    state: '{{ __volume_state }}'
  when: not _hub_nfs | bool

- name: Manage the Automation Hub tmp volume
  containers.podman.podman_volume:
    name: hub_tmp
    state: '{{ __volume_state }}'
  when: _hub_nfs | bool

- name: Manage the Automation Hub nginx volume
  containers.podman.podman_volume:
    name: hub_nginx
    state: '{{ __volume_state }}'
...
