---
- name: "Block to be executed only when connected against an AAP instance (not Tower)"
  when: is_aap
  block:
    - name: Get the organization ID
      ansible.builtin.set_fact:
        __controller_organization_id: "{{ lookup(controller_api_plugin, 'organizations',
                                                 query_params={'name': orgs},
                                                 host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs)
                                       }}"

    - name: "Get the API list of all Execution Environments in Organization {{ orgs }}"
      ansible.builtin.set_fact:
        __controller_api_execution_environments: "{{ query(controller_api_plugin, 'execution_environments',
                                                           query_params={'organization': __controller_organization_id.id},
                                                           host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                                           return_all=true, max_objects=query_controller_api_max_objects)
                                                  }}"

    - name: "Find the difference of Execution Environment between what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        __execution_environments_difference: "{{ query(controller_role_plugin,
                                                       api_list=__controller_api_execution_environments, compare_list=controller_execution_environments,
                                                       with_present=include_present_state, set_absent=true) | flatten
                                              }}"

    - name: "Set execution_environment's list to be configured"
      ansible.builtin.set_fact:
        controller_execution_environments: "{{ __execution_environments_difference }}"
...
