---
- name: "Get the current controller user to determine if it is super-admin"
  ansible.builtin.set_fact:
    __controller_api_current_user_check_is_admin: "{{ lookup(controller_api_plugin, 'me',
                                                             host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs)
                                                   }}"

- name: "Instance Group differences (block)"
  when:
    - __controller_api_current_user_check_is_admin.is_superuser
  block:
    - name: "Get the API list of all instance_groups"
      ansible.builtin.set_fact:
        __controller_api_instance_groups: "{{ query(controller_api_plugin, 'instance_groups',
                                                    host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                                    return_all=true, max_objects=query_controller_api_max_objects)
                                           }}"

    - name: "Find the difference of Instance Groups between what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        __instance_groups_difference: "{{ query(controller_role_plugin,
                                                api_list=__controller_api_instance_groups,
                                                compare_list=controller_instance_groups,
                                                with_present=include_present_state,
                                                set_absent=true) | flatten
                                       }}"

    - name: "Sets the difference of Instance Groups between what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        controller_instance_groups: "{{ __instance_groups_difference }}"
...
