---
- name: Collect services facts
  hosts: automationcontroller:automationeda:automationgateway:automationhub:database:execution_nodes:redis
  gather_facts: false
  become: false
  tasks:
    - name: Gather regular user uid and home dir
      ansible.builtin.setup:
        filter:
          - 'ansible_user_uid'
          - 'ansible_user_dir'

    - name: Get service facts
      ansible.builtin.service_facts:
      become: true

- name: Uninstall the Automation Controller
  hosts: automationcontroller
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall the automation controller
      ansible.builtin.import_role:
        name: automationcontroller
        tasks_from: uninstall.yml

- name: Uninstall the Automation Hub
  hosts: automationhub
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall the automation hub
      ansible.builtin.import_role:
        name: automationhub
        tasks_from: uninstall.yml

- name: Uninstall the Automation EDA
  hosts: automationeda
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall the automation eda
      ansible.builtin.import_role:
        name: automationeda
        tasks_from: uninstall.yml

- name: Uninstall receptor
  hosts: automationcontroller:execution_nodes
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall receptor
      ansible.builtin.import_role:
        name: receptor
        tasks_from: uninstall.yml

- name: Uninstall the Automation Gateway
  hosts: automationgateway
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall Automation Gateway
      ansible.builtin.import_role:
        name: automationgateway
        tasks_from: uninstall.yml

- name: Uninstall redis cluster
  hosts: redis
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall redis cluster tcp socket
      ansible.builtin.include_role:
        name: redis
        tasks_from: uninstall.yml
      vars:
        redis_unix_socket: false
        redis_cluster: true
      when: redis_mode | default('cluster') == 'cluster'

- name: Uninstall redis
  hosts: automationcontroller:automationeda:automationgateway:automationhub
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall redis unix socket
      ansible.builtin.include_role:
        name: redis
        tasks_from: uninstall.yml
      when: >
        inventory_hostname in groups.get('automationcontroller', []) or
        inventory_hostname in groups.get('automationhub', []) or
        (inventory_hostname in groups.get('automationeda', []) and groups.get('automationeda', []) | length == 1)

    - name: Uninstall redis tcp socket
      ansible.builtin.include_role:
        name: redis
        tasks_from: uninstall.yml
      vars:
        redis_unix_socket: false
      when:
        - redis_mode | default('cluster') == 'standalone'
        - inventory_hostname == groups['automationgateway'] | first

- name: Uninstall pcp
  hosts: automationcontroller:automationhub:automationeda:automationgateway:database:redis
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall pcp
      ansible.builtin.include_role:
        name: pcp
        tasks_from: uninstall.yml

- name: Uninstall the database
  hosts: database
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall postgresql
      ansible.builtin.import_role:
        name: postgresql
        tasks_from: uninstall.yml

- name: Remove service leftovers
  hosts: automationcontroller:automationeda:automationgateway:automationhub
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Run ostree tasks
      ansible.builtin.import_role:
        name: common
        tasks_from: ostree.yml

    - name: Remove python packages used by collections
      ansible.builtin.package:
        name:
          - python3-psycopg2
        state: absent
      become: true
      when: not ostree | bool

- name: Uninstall common container components
  hosts: automationcontroller:automationeda:automationgateway:automationhub:database:execution_nodes:redis
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Uninstall podman
      ansible.builtin.import_role:
        name: common
        tasks_from: uninstall.yml
...
