---
- name: Restart hub api
  ansible.builtin.systemd:
    name: automation-hub-api.service
    scope: user
    state: restarted

- name: Restart hub content
  ansible.builtin.systemd:
    name: automation-hub-content.service
    scope: user
    state: restarted

- name: Restart hub web
  ansible.builtin.systemd:
    name: automation-hub-web.service
    scope: user
    state: restarted

- name: Restart hub workers
  ansible.builtin.systemd:
    name: 'automation-hub-worker-{{ item }}.service'
    scope: user
    state: restarted
  loop: '{{ hub_workers_range }}'
...
