download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/infra-ah_configuration-2.0.6.tar.gz
format_version: 1.0.0
name: ah_configuration
namespace: infra
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.6
version_url: /api/v3/plugin/ansible/content/published/collections/index/infra/ah_configuration/versions/2.0.6/
