---
- name: Create the performance co-pilot container
  containers.podman.podman_container:
    name: pcp
    image: '{{ _pcp_image }}'
    generate_systemd:
      container_prefix: ''
      path: '{{ ansible_user_dir }}/.config/systemd/user'
      separator: ''
    log_driver: '{{ container_log_driver }}'
    network: host
    systemd: always
    volume: '{{ _pcp_volume }}'
    label: '{{ _autoupdate_label }}'
    state: created
  notify: Restart pcp
...
