---
- name: Manage pcp pmcd firewalld port
  ansible.posix.firewalld:
    port: '{{ pcp_pmcd_port }}/{{ pcp_protocol }}'
    permanent: true
    state: '{{ __firewalld_state }}'
    immediate: true
    zone: '{{ pcp_firewall_zone }}'
  become: true
  when:
    - ansible_facts.services.get('firewalld.service', {}) | length
    - ansible_facts.services['firewalld.service']['status'] == 'enabled'

- name: Manage pcp pmcd firewalld port
  ansible.posix.firewalld:
    port: '{{ pcp_pmproxy_port }}/{{ pcp_protocol }}'
    permanent: true
    state: '{{ __firewalld_state }}'
    immediate: true
    zone: '{{ pcp_firewall_zone }}'
  become: true
  when:
    - ansible_facts.services.get('firewalld.service', {}) | length
    - ansible_facts.services['firewalld.service']['status'] == 'enabled'
...
