---
- name: Set pcp facts
  ansible.builtin.include_tasks: facts.yml

- name: Configure pcp
  ansible.builtin.include_tasks: config.yml

- name: Handle container image update
  ansible.builtin.include_tasks: update.yml

- name: Configure containers
  ansible.builtin.include_tasks: containers.yml

- name: Ensure pcp container is enabled and started
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_enabled: true
    __systemd_state: started

- name: Add firewalld rules
  ansible.builtin.include_tasks: firewalld.yml
  vars:
    __firewalld_state: enabled
...
