download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/infra-controller_configuration-2.9.0.tar.gz
format_version: 1.0.0
name: controller_configuration
namespace: infra
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.9.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/infra/controller_configuration/versions/2.9.0/
