---
### container
container_log_driver: journald

### common
aap_volumes_dir: '{{ ansible_user_dir }}/aap'

### hub
hub_firewall_zone: public
hub_data_dir: '{{ aap_volumes_dir }}/hub/data'
hub_conf_dir: '{{ aap_volumes_dir }}/hub/etc'
hub_container_requires:
  - redis-unix
hub_api_port: 24817
hub_api_workers: '{{ ansible_processor_vcpus | default(4) | int * 2 + 1 }}'
hub_content_port: 24816
hub_content_workers: '{{ ansible_processor_vcpus | default(4) }}'
hub_gunicorn_timeout: 90
hub_workers: 2
hub_workers_range: '{{ range(1, hub_workers | int + 1, 1) | list }}'
hub_collection_auto_sign: false
hub_collection_signing: false
hub_collection_signing_service: ansible-default
hub_container_signing: false
hub_container_signing_service: container-default
hub_seed_collections: true
hub_extra_settings: []

### storage
hub_storage_backend: file
hub_azure_container: pulp
hub_azure_extra_settings: {}
hub_s3_bucket_name: pulp
hub_s3_extra_settings: {}

### postinstall
hub_postinstall_ignore_files: []
hub_postinstall_repo_ref: main
hub_postinstall_async_delay: 1
hub_postinstall_async_retries: 30

### database
hub_pg_username: pulp
hub_pg_database: pulp
hub_pg_port: 5432
hub_pg_sslmode: prefer
hub_pg_cert_auth: false

### redis
hub_redis_cache_db: 2

### nginx
hub_nginx_conf_dir: '{{ aap_volumes_dir }}/hub/nginx/etc'
hub_nginx_disable_https: false
hub_nginx_disable_hsts: false
hub_nginx_hsts_max_age: 63072000
hub_nginx_http_port: 8081
hub_nginx_https_port: 8444
hub_nginx_https_protocols:
  - TLSv1.2
  - TLSv1.3
hub_nginx_client_max_body_size: 20m
hub_nginx_user_headers: []

### TLS CA
ca_trust_bundle: /etc/pki/tls/certs/ca-bundle.crt

### NFS
hub_shared_data_mount_opts: 'rw,sync,hard'
...
