---
- name: Restart eda api
  ansible.builtin.systemd:
    name: automation-eda-api.service
    scope: user
    state: restarted

- name: Restart eda daphne
  ansible.builtin.systemd:
    name: automation-eda-daphne.service
    scope: user
    state: restarted
  when: eda_type in ['hybrid', 'worker']

- name: Restart eda web
  ansible.builtin.systemd:
    name: automation-eda-web.service
    scope: user
    state: restarted

- name: Restart eda workers
  ansible.builtin.systemd:
    name: 'automation-eda-worker-{{ item }}.service'
    scope: user
    state: restarted
  loop: '{{ eda_workers_range }}'
  when: eda_type in ['hybrid', 'worker']

- name: Restart eda activation workers
  ansible.builtin.systemd:
    name: 'automation-eda-activation-worker-{{ item }}.service'
    scope: user
    state: restarted
  loop: '{{ eda_activation_workers_range }}'
  when: eda_type in ['hybrid', 'worker']

- name: Restart eda scheduler
  ansible.builtin.systemd:
    name: automation-eda-scheduler.service
    scope: user
    state: restarted
  when: eda_type in ['hybrid', 'worker']
...
