---
- name: Restart controller rsyslog
  ansible.builtin.systemd:
    name: automation-controller-rsyslog.service
    scope: user
    state: restarted

- name: Restart controller task
  ansible.builtin.systemd:
    name: automation-controller-task.service
    scope: user
    state: restarted

- name: Restart controller web
  ansible.builtin.systemd:
    name: automation-controller-web.service
    scope: user
    state: restarted
...
