---
- name: Update CA trust
  containers.podman.podman_container:
    name: update-ca-trust
    image: '{{ _images | first }}'
    command: 'update-ca-trust'
    detach: false
    rm: true
    log_driver: journald
    user: root
    volume: '{{ _ca_volumes }}'
...
