---
- name: Login to the registry
  containers.podman.podman_login:
    authfile: '{{ ansible_user_dir }}/.config/containers/auth.json'
    username: '{{ registry_username }}'
    password: '{{ registry_password }}'
    registry: '{{ registry_url }}'
    tlsverify: '{{ registry_tls_verify }}'
  environment:
    HTTP_PROXY: "{{ http_proxy | default('') }}"
    HTTPS_PROXY: "{{ https_proxy | default('') }}"
    NO_PROXY: "{{ no_proxy | default('') }}"
...
