---
gateway_configuration_dispatcher_roles:
  - role: authenticator
    var: ansible.gateway_configuration.authenticators
    tags: authenticators
  - role: authenticator_map
    var: ansible.gateway_configuration.authenticator_maps
    tags: authenticator_maps
  - role: ansible.gateway_configuration.settings
    var: gateway_settings
    tags: settings
  - role: users
    var: ansible.gateway_configuration.gateway_user_accounts
    tags: users
  - role: http_ports
    var: ansible.gateway_configuration.http_ports
    tags: http_ports
  - role: organizations
    var: ansible.gateway_configuration.organizations
    tags: organizations
  - role: service_clusters
    var: ansible.gateway_configuration.gateway_service_clusters
    tags: service_clusters
  - role: service_keys
    var: ansible.gateway_configuration.gateway_service_keys
    tags: service_keys
  - role: service_nodes
    var: ansible.gateway_configuration.gateway_service_nodes
    tags: service_nodes
  - role: services
    var: ansible.gateway_configuration.gateway_services
    tags: services
  - role: role_user_assignments
    vars: ansible.gateway_configuration.gateway_role_user_assignments
  - role: routes
    vars: ansible.gateway_configuration.gateway_routes
    tags: routes
  - role: teams
    vars: ansible.gateway_configuration.gateway_teams
    tags: teams
...
