---
- name: Create the postgresql configuration
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: '{{ postgresql_conf_dir }}/postgresql.conf'
    mode: '0644'
  notify: Restart postgresql
...
