---
- name: Set postgresql facts
  ansible.builtin.include_tasks: facts.yml

- name: Configure podman secrets
  ansible.builtin.include_tasks: secrets.yml

- name: Create podman volumes
  ansible.builtin.include_tasks: volumes.yml
  vars:
    __volume_state: present

- name: Configure TLS
  ansible.builtin.include_tasks: tls.yml
  when: not postgresql_disable_tls | bool

- name: Configure postgresql
  ansible.builtin.include_tasks: config.yml

- name: Handle container image update
  ansible.builtin.include_tasks: update.yml

- name: Configure containers
  ansible.builtin.include_tasks: containers.yml

- name: Ensure postgresql container is enabled and started
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_enabled: true
    __systemd_state: started

- name: Add firewalld rules
  ansible.builtin.include_tasks: firewalld.yml
  vars:
    __firewalld_state: enabled
...
