---
- name: Create the postgresql admin password secret
  containers.podman.podman_secret:
    name: postgresql_admin_password
    data: '{{ postgresql_admin_password }}'
    skip_existing: '{{ _podman_idempotence | ternary(omit, true) }}'
    force: '{{ _podman_idempotence | ternary(omit, true) }}'
...
