---
- name: Manage postgresql container via systemd
  ansible.builtin.systemd:
    name: postgresql.service
    state: '{{ __systemd_state | default("started") }}'
    enabled: '{{ __systemd_enabled | default(true) }}'
    scope: user
    daemon_reload: true
...
